{% set name = "go-git" %}
{% set version = "5.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-git/go-git/archive/v{{ version }}.tar.gz
  sha256: 1877e8621a012d17a76537540cf9dc9d05498cb496c47a5dc10ad053c1ccd105

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - go-git version

about:
  home: https://github.com/go-git/go-git
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  dev_url: https://github.com/go-git/go-git

extra:
  recipe-maintainers:
    - danielnachun
