schema_version: 1

context:
  version: "5.19.0"

package:
  name: go-git
  version: ${{ version }}

source:
  url: https://github.com/go-git/go-git/archive/v${{ version }}.tar.gz
  sha256: cd1de56c69c3a9ba1e608cce0c35720ba7f714995b62fecdf4272a4c215e5406

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - go-git version

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  homepage: https://github.com/go-git/go-git
  repository: https://github.com/go-git/go-git

extra:
  recipe-maintainers:
    - danielnachun
