schema_version: 1

context:
  version: "5.19.2"

package:
  name: go-git
  version: ${{ version }}

source:
  url: https://github.com/go-git/go-git/archive/v${{ version }}.tar.gz
  sha256: 6c4524af67065f3b28708c3a3aa0931c43aa17c0cddd5762a38717e1286e8ed8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - go-git version

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  homepage: https://github.com/go-git/go-git
  repository: https://github.com/go-git/go-git

extra:
  recipe-maintainers:
    - danielnachun
