schema_version: 1

context:
  version: "5.19.1"

package:
  name: go-git
  version: ${{ version }}

source:
  url: https://github.com/go-git/go-git/archive/v${{ version }}.tar.gz
  sha256: 91b44587081b94cee4c379f7eaad28e660384f77c334da57cf53551e7e710596

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - go-git version

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  homepage: https://github.com/go-git/go-git
  repository: https://github.com/go-git/go-git

extra:
  recipe-maintainers:
    - danielnachun
